### ISSUE TITLE
Minor Issues on the Event Proposals Page

### ISSUE THREAD

**Issue by PhilipKelley** [neinteractiveliterature/intercode#1302]
Some minor issues on the Event Proposals page:

New column Duration would be easier to read if text were centered, or perhaps right-aligned. As is, the numbers are vry close to the Capacity column numbers, making both difficult to read.

When columns are selected/deselected, a number appears in the “Columns” dropdown box. For example, when all are selected, I get a “-1” in a blue box; when 2 are de-selected, I get a “1”. No value appears when all but 1 are selected. Is this intentional? (Saw something similar on other pages, too.)

**Comment by nbudin** [comment]
The number is intentional - it's supposed to show you how many columns are hidden.  However, there was a counting error causing the -1 to appear on this particular page.  

Relatedly, the "duration" column was supposed to appear by default, but wasn't.  I've fixed that as well as the counting error, and made the "duration" column much narrower and right-aligned, which will hopefully help with the readability issues.
