### ISSUE TITLE
Waitlisting for games with no potential slots

### ISSUE THREAD

**Issue by ChristopherBass** [neinteractiveliterature/intercode#1455]
https://s.interconlarp.org/events/76-athena-s-chosen
This game has no male slots - but male slots are still displayed as an option, and you can successfully waitlist for a male slot, even though signups aren't active yet.

Expected: Either grey out or don't show signup buttons for options that have 0 maximum players, and don't allow waitlisting before signups have even started.

**Comment by nbudin** [comment]
Hey @ChristopherBass!  Thanks for reporting this; it's a huge oversight on my part.

There were actually two separate problems here:

1. Waitlist signups were skipping the `max_signups_allowed` validation.  At the current time, the only way to trigger that (I think) was by doing what you did, since none of the games have actual confirmed signups yet.  I've fixed that in the code, and the fix should go out to production shortly.
2. Athena's Chosen was misconfigured: it shouldn't have had a "male role" bucket, since it had no flex slots.  (It's valid to have a zero-size regular bucket if the event has flex slots, but not if it doesn't.)  We should have caught this in the proposal process, but @dkapell has fixed it now on the site.
