### ISSUE TITLE
Add scheduled times to Title and Order Added (Newest/Oldest) sorts on Events page

### ISSUE THREAD

**Issue by TheCrowMother** [neinteractiveliterature/intercode#1456]
Would be useful to check for conflicts with games already signed up for/running.

**Comment by nbudin** [comment]
To update you on the status of this: I took a pass at it yesterday, but wasn't happy with how the results looked (things were pretty cluttered after doing it).  Going to try again with a different approach, but the results won't appear until at least tomorrow, since I'm trying to avoid deploying anything but bug fixes during Intercon signup days.

**Comment by rizwank** [comment]
I like that the current exists at least. Clustering them by time slot or starting time slot would be nice. In my own sheet that I extracted from your JSON, I lumped them as 'Saturday morning/afternoon/evening' - but that was an arbitrary classification; not sure if you have a better grouping available.

**Comment by nbudin** [comment]
OK, we now have the scheduled time in the upper right of each event header!  (Or just below the title, if there's not room on the upper right.)
