### ISSUE TITLE
Able to double dip for first event with 2 events / 1 event+1waitlist

### ISSUE THREAD

**Issue by rizwank** [neinteractiveliterature/intercode#1464]
During 1st round signups, myself and another went for event A.
We both were waitlisted.
We then tried to sign up for event B. (I did it on a separate browser on a separate machine. My friend did it on the same machine.)

We were allowed to sign up for event B, meaning we had a waitlist and an event signed up for; while the total event count was only 1. This has not been the policy in the past.

Event A had some movements and we were then cleared from the waitlist to the main event, meaning we are now signed up for both events when the event count was only 1.

After this stage, however, we could NOT join the waitlist or the event for an Event C.

I'll maintain my aberrant status for a few days if it aids debugging, but please don't forcibly remove me from a game unless we've talked about which one I want to keep. =) (hint, @nbudin you are running the one I want to keep)

**Comment by nbudin** [comment]
Copied from @dkapell's Facebook post:

> IMPORTANT: There’s currently an issue which allows everyone to be waitlisted for an event as well as signed up for another larp, which is more than the single signup that should be possible right now.
We are going to resolve this shortly (tomorrow). When we do, we will remove the waitlist signup from anyone who is in a larp as well. If you want to preserve your waitlist signup instead of your in-the-game signup, simply drop out of the larp that you have signed up for.
If you have any questions about this, please let me know.
