### ISSUE TITLE
Schedule with count colors me confused

### ISSUE THREAD

**Issue by diewald** [neinteractiveliterature/intercode#1484]
If you look at the current schedule with counts, there are a bunch of games marked with light blue. The key to the map says that they are "unlimited capacity," but that seems wrong. (e.g. "Radiance Rose," "Lancelot," and more.) The game that I'm in (Falkonia) is also full, and it's the dark blue of "Full." Ops and the Intercon Dance are the dark blue of "Full," because they are, with zero signups. 

It's a minor annoyance, but it's confusing.

**Comment by dkapell** [comment]
Ops are showing up as full because their one bucket is flagged as 'not counted' so it doesn't count towards limited numbers of signups.  The dance is full because it doesn't have a signups bucket.

I agree that Radiance Rose, and others are being colored with the 'Unlimited' color instead of the 'Full' color.

For games with not counted / unlimited signups, I propose:
1) If a game has counted signups as well as non counted or unlimited, display status based on the counted bucket(s)
2) if a game only has unlimited signups, display status as unlimited
3) if a game only has non-counted signups, display status based on the non-counted bucket(s)
4) if a game has a non-counted bucket and an unlimited bucket - display status based on the not-counted bucket(s)

**Comment by nbudin** [comment]
This is a known issue: see #1475.  Since there's better description and discussion on there, I'll close _that_ one as a duplicate. 😄

**Comment by nbudin** [comment]
I'm about to push a release which does exactly as @dkapell outlined above, except for point 4.  This turns out to be much trickier to do, and instead, for now, I'm having it treat games with unlimited buckets as fully-unlimited.  If a further change is desired, we can open a followup ticket.
