### ISSUE TITLE
Become User escalation vulnerability

### ISSUE THREAD

**Issue by jhartwin** [neinteractiveliterature/intercode#1875]
This bug allows one privileged user to permanently become another, not as Alice signed in as Bob, but actually as Bob signed in as himself.

Steps to recreate:
Become a user with become user privs.
As that user, become a different user.
Click the Revert button.
You should now be signed in as that user, as if you had entered their username and password.

**Comment by jhartwin** [comment]
(Not sure if this is actually worth fixing, but Dave asked me to file a bug)

**Comment by nbudin** [comment]
I think it's true that this is a real security issue; it's a relatively minor one because you need to have "become user" privs in the first place to be able to trigger it, but it is indeed an actual problem.  It shouldn't be too hard to disable "become user" when you're currently assuming an identity, though.

**Comment by jhartwin** [comment]
Oh, it's absolutely a legitimate vulnerability, and in another context I'd be much less sanguine about this. If, e.g., I had the ability to modify financial data, I could use this vulnerability to frame another admin for embezzling. I just don't think, in this context, it needs to be particularly high priority.

**Comment by nbudin** [comment]
Actually, easier idea: I'm just gonna make it keep the original identity if one exists, and let you "become" another user while keeping your original account as the identity assumer.
