### ISSUE TITLE
Unable to add users to Intercon T

### ISSUE THREAD

**Issue by chadberg** [neinteractiveliterature/intercode#1882]
We are starting to get some rollover requests for Intercon T. To rollover a badge, the person must exist in the Intercon T attendee list. This works great if the person has already logged into the T site. In theory I should be able to use the 'Add attendee' button at the top of the attendee list and search for someone already in the site database to add them to Intercon T so I can then roll over the badge. But the search box that appears when the 'Add attendee' button is pressed returns no results when I search by any part of the name or email address for the person I want to add. I presume this is not actually T specific and is a more generalized issue, and the failing could be documentation and training on how to use this feature rather than a technical one.

**Comment by nbudin** [comment]
Copying comments from Slack:

This is, believe it or not, somewhat intentional.  In order to let non-NEIL cons onto the site, I had to temporarily break that feature for everyone but site admins while building out the Organizations feature (which would let us reenable it).

It's obviously not ideal to have the UI enabled while the feature is disabled, and if #1619 doesn't ship relatively soon I'll disable the UI.  But for now, that feature is coming along well and so hopefully I can just get this working again soon.

**Comment by dkapell** [comment]
This functionality is temporarily disabled, due to dice bubble as per
conversation on the NEIL board list
