### ISSUE TITLE
Pre-defined buckets different than Intercon default

### ISSUE THREAD

**Issue by Quinn-D** [neinteractiveliterature/intercode#2205]
The bucket options on a proposal form show the full Intercon default options.  Would it be possible to be able to configure what registration policies show and a way to make a pre-filled custom bucket?

Be-Con 2019 would like to have the limited slots and a pre-filled custom bucket of:
Player Defined Gender
Female
Male
Other Gender

That custom bucket option is possible using the regular custom bucket policy, but would be very confusing for attendees not familiar with the system.

**Comment by nbudin** [comment]
Hey @Quinn-D!  A few questions:

1. If I'm reading this correctly, you want to still have the "limited slots" (just a "signups" button) option available to your GMs.  Is that correct?
2. Susan had mentioned not wanting to allow custom buckets at all.  Since you didn't mention it here, I just want to confirm that that is the case.

**Comment by Quinn-D** [comment]
We are open to various implementations. A prefilled custom bucket (with those 4 types) is one idea  I was thinking about it as a extension of what exists, that admins could create a policy using it for everyone.  If that's not the best path, no worries.

We would like to have only a single registration policy which has those 4 buckets and is straightforward for users.

**Comment by nbudin** [comment]
Ok.  To make you aware, under what you’re requesting, any games that have those four buckets in them will have all the signup buttons.  So for example, let’s say someone is running Spring River, which has only non-gendered roles.  Users would still see buttons for “male role”, “female role”, etc.  if they clicked those, they would simply overflow into the “flex” bucket (which in your case, I guess, would be the “player-defined gender” bucket).

In Be-Con’s case, this would matter less because the signup buttons would only be used after Be-Con had assigned everyone games, for switching.  So it might not be a big deal, but I want to make sure you understand the ramifications of the request you’re making before we implement it.
