### ISSUE TITLE
missing mailing list for game

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#2838]
https://t.interconlarp.org/events/4508-wrestle-mageddon-backstage-heel-turns
should have created
wrestlelarp@events.t.interconlarp.org
but didn't

**Comment by nbudin** [comment]
Turns out this was a case of user error: the user had chosen an email address at events.t.interconlarp.org but not chosen the "create and manage the mailing list for me" option.  I could imagine doing a check on this and automatically fixing it if they picked the domain where we make team mailing lists, but that seems out of scope for this.  In any case, there's not actually a bug here.
