### ISSUE TITLE
Update notification language for SMS

### ISSUE THREAD

**Issue by marleighnorton** [neinteractiveliterature/intercode#3218]
Player:
Hi [playername], a slot has opened in [eventname].  As a result, you have been removed from the waitlist and are signed up.

Please contact your GMs as soon as possible to confirm your attendance and receive any event materials.
GMs: [GM Names]
E-mail: [event e-mail]

If you can't make it after all, please withdraw so that others can have a chance to get in.  You can withdraw via the event page: [event URL]

GM:
Hi [GM Name], [playername] has been signed up for [event].  They have been asked to reach out to you at [event e-mail] to confirm their attendance.

You may also reach out to them directly at [e-mail]

**Comment by nbudin** [comment]
@marleighnorton: I've updated the player-facing text message to (more or less) match this.  The GM-facing one, as it turns out, is a little trickier.  We send it out as a result of the _withdrawal_; there isn't a separate one for the pull-in.

One thing I can do is to add emails to the list of pulled-in signups as well as a note that the players have been asked to reach out.  Would that be good from your POV?

**Comment by marleighnorton** [comment]
I'm not quite sure what you mean by adding e-mails to the list of pulled in signups.  What would the message look like then?

**Comment by nbudin** [comment]
Here's an example:

```
Joe Smith has withdrawn from [event name].  (Previously, they were confirmed.)

To fill the vacancy, the following signups were moved:
Paula Rodriguez (paularodriguez@example.com): waitlisted → confirmed 

We've sent messages to newly confirmed attendees asking them to reach out to you at [event email] to confirm their attendance.

As of this withdrawal, this event run has:
Signed up: 30
```

**Comment by marleighnorton** [comment]
Sure, that works.

**Comment by nbudin** [comment]
OK great, I'll do the deed.  Thanks @marleighnorton!

**Comment by nbudin** [comment]
This is now all set in production.
