### ISSUE TITLE
Idea - 'Exempt from Flex' checkbox for a bucket

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#483]
I haven't thought about what that means, but it would allow:
2 female PCs
2 male PCs
8 flex PCs
10 or unlimited NPCs

**Comment by nbudin** [comment]
That seems coherent as a concept but maybe too much complexity to put on GMs?  I think what I'd say is let's see what the GMs this year decide to do, and what they ask us.  If there's a desire for this feature, it shouldn't be too tricky to add, since the way EventSignupService is written makes it pretty straightforward.

**Comment by dkapell** [comment]
do not_counted buckets count for flex at this point?  I know they don't for no preference

**Comment by nbudin** [comment]
@dkapell: not_counted buckets will never put you in flex, if you request them.

**Comment by dkapell** [comment]
so this is now resolved.  if you have a not_counted bucket with 10 slots, and it's full, and a flex bucket with 10 slots, and it's empty, and you select the not_counted bucket, you will get waitlisted, not signed up as flex, right?

The other direction is resolved because no preference won't drop you in the not_counted bucket

**Comment by nbudin** [comment]
Yup, that's right.  That's great news, I'll go ahead and close this.
