### ISSUE TITLE
New user could not figure out how to sign up for Summer LARPin'

### ISSUE THREAD

**Issue by diewald** [neinteractiveliterature/intercode#4956]
<img width="875" alt="Screen Shot 2021-04-27 at 11 45 33 AM" src="https://user-images.githubusercontent.com/6187336/116271798-50cf9080-a74e-11eb-8da9-e28a6308c9cd.png">

Having the log in / sign up action hidden under a tiny icon on the top right is hard to find. Sign up should be a huge "can't miss me" button on the home page.

<img width="980" alt="Screen Shot 2021-04-27 at 11 29 50 AM" src="https://user-images.githubusercontent.com/6187336/116271137-b4a58980-a74d-11eb-9c76-c17c54d47010.png">

**Comment by nbudin** [comment]
Agreed, it's not super great.  What do you think about replacing that icon (when logged out) with a button saying something like "log in/sign up"?

**Comment by dkapell** [comment]
I think that's a good solution.

Jeff - Anything that goes on the home page is, of course, put there by the owner of the particular site, so we are limited to putting things in the toolbar, like Nat suggested, or making recommendations to site owners about what they should have on the main page, and giving them the widget we designed for the Intercon/extracon site.

**Comment by nbudin** [comment]
Yeah, although in this case, I did design this site, so it's really all on me for this one 😁

**Comment by diewald** [comment]
Nat, I like the solution, especially if that makes it a standard across all the sites. 

Dave, is there a template that we give new owners, or a default layout? If so, we could populate it with a skeleton including internal documentation about things we suggest or have learned. (_e.g._ this signup widget makes it obvious how people can sign up.)

**Comment by nbudin** [comment]
OK, I went ahead and made this change locally (not in production yet).  Here's what it looks like on an iPhone X-sized screen:

![Screen Shot 2021-05-01 at 9 15 38 AM](https://user-images.githubusercontent.com/7477/116788330-d197d080-aa5d-11eb-9c66-79025fa1cfe0.png)

As you can see, the button text pushes the navigation bar to two rows.  I don't think that's necessarily the worst thing ever, but it is why I hadn't done this to begin with.  Happy to hear thoughts; if nobody has strong opinions I'm going to go ahead with this change, because I think two rows is the lesser evil (compared to not being able to find the login button).

**Comment by nbudin** [comment]
The new version of this button is now in production!

**Comment by diewald** [comment]
Thanks, as always, for your excellent work!
