### ISSUE TITLE
Submit proposal button flickers on keyup

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#529]
because you're re-validating the form with each keypress, the submit button flickers.  Would it be possible/easy to have it only disable if validation fails, rather than when validation begins?

**Comment by nbudin** [comment]
It’s not validation, it’s a save in progress.  I don’t want to allow form submission while a save is happening; however, there might be invisible ways to do that - not sure.
		
		

		Nat
	




On Sun, Feb 4, 2018 at 2:50 PM -0800, "dkapell" <notifications@github.com> wrote:












because you're re-validating the form with each keypress, the submit button flickers.  Would it be possible/easy to have it only disable if validation fails, rather than when validation begins?

**Comment by dkapell** [comment]
one possibility would be to set a flag in JS that save is in progress, and if that's true when you get a submit event, delay for half of a second and try again.  (or just don't accept the submit, and the user will click again )
