### ISSUE TITLE
Idea: Allow a bucket to be marked as not counting for signups

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#633]
To allow people to sign up for NPC shifts early in the signup process.

**Comment by nbudin** [comment]
This is an interesting one, and probably requires more discussion.  It also brings to mind that, right now, we have no way of saying that an *event* doesn't count towards maximum signups (IIRC), so that right now, Ops shifts would count.  That's obviously a big problem, but it's not clear to me whether the solution to it is to do this on the bucket level (so that you would set up the single bucket in Ops to not count) or on the event level, or possibly allow both, with the bucket overriding the event.

**Comment by dkapell** [comment]
Yes and this was a placeholder for a longer discussion we should have about
this, because I was asked

**Comment by dkapell** [comment]
Option, for later discussion - Unlimited buckets don't count towards limited signups. (this covers signing up for NPCing games, and prevents new attendees from burning signup selections on buckets that they literally can not miss out on.

**Comment by dkapell** [comment]
This would also exempt the bucket from being counted towards max players in the proposal list, calculations of if it can be run, etc.  so:
If a bucket is marked as not-counted:

- It does not count towards the number of games you can sign up for
- It does not count towards the maximum players in the game (on the proposal form, on the proposal list, and on the schedule progress bar )
- It is exempted from 'No Preference' signups, even if it's not an unlimited bucket
- It does count for being signed up at a given time, same as any other signup
