### ISSUE TITLE
Make 'unpaid' checkbox sticky

### ISSUE THREAD

**Issue by chadberg** [neinteractiveliterature/intercode#662]
When navigating around applying tickets to people the checkboxes for the attendee advanced search are not sticky, so I am having to recheck 'unpaid' every time. Can we make that a sticky set and cookie it? Especially because they are hidden behind the 'advanced' section I have to take multiple extra steps for each person.

**Comment by nbudin** [comment]
This is hopefully resolvable in #639.

**Comment by nbudin** [comment]
This is at least somewhat resolved by the new attendees table (you can use the back button to get back to the previous filter set, and you can bookmark a filter set for future use).  It still isn't actually sticky, but I think maybe the current state is good enough for this use case, and better in some ways (since it's very transparent what'll happen when you go to any given URL).

@chadberg, let me know if you have further suggestions now that the new attendees table is released.
