### ISSUE TITLE
Resolve inconsistent language re: ticket/badge

### ISSUE THREAD

**Issue by chadberg** [neinteractiveliterature/intercode#663]
In some screens we refer to issuing a badge, badge type, and creating different sorts of badges. In other places, such as the attendee list, we refer to a ticket. There's probably some philosophical discussion to be had around which we should use, where and why, but it should be consistent when we are referring to the same thing. (Especially considering we also have a physical thing called a badge).

**Comment by chadberg** [comment]
I think this is probably linked to #526 which has been closed already.

**Comment by dkapell** [comment]
Yes, this is globally configurable, but we may have missed some spots where
ticket is hard coded.

On Mar 5, 2018 12:40 PM, "Chad Bergeron" <notifications@github.com> wrote:

I think this is probably linked to #526
<https://github.com/neinteractiveliterature/intercode/issues/526> which has
been closed already.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/neinteractiveliterature/intercode/issues/663#issuecomment-370557154>,
or mute the thread

**Comment by nbudin** [comment]
Right, I meant to open a followup ticket about this.  I'm fairly confident the attendee list is the only spot where it says "ticket" regardless of the setting, and the reason it does it is because of limitations from datagrid, a Rails library we use for pages like this.  (I couldn't figure out a reasonable way to get dynamic column names in datagrid that wasn't massively painful.)

I'm not happy with datagrid in general, and there's a ticket already about switching from it to react-table (#639).  I'd like to defer making this change to when we do that.

**Comment by chadberg** [comment]
I see little harm in deferring if it is only showing on the internal screen for the time being.

**Comment by nbudin** [comment]
Should have closed this when I released the new version of the attendees table - it's fixed now.
