### ISSUE TITLE
Provide a mechanism for post-event surveys

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#7]
It would be very useful for many type of events to have a simple survey go out to the participants after the event is complete.

**Comment by diewald** [comment]
Our friends at Consequences have already implemented something to do this in their copy of the website.

**Comment by nbudin** [comment]
I can see two potential ways to go about this:

1. Allow the built-in custom form system in Intercode to be used to administer arbitrary surveys.  (It's currently not the world's best survey system, since it has a very user-unfriendly admin UI (which will eventually not be true), has no support for skip logic (which it might never need), and honestly isn't really designed for this kind of thing.)
2. Integrate with some third-party survey tool.  (Probably Google Forms, since it seems like it's good enough for most things and has an API for apps already.)

I'd personally lean towards a third-party solution, since we're never going to be able to compete on features with something like Google Forms.  My question is: if we were to do that, what kind of integration would actually be needed/helpful?  Perhaps some kind of feature to send survey invitations to all attendees of a convention?  Or, possibly, an automatic "closedown" task that runs once the convention is complete that will _automatically_ send out survey invitations?

**Comment by nbudin** [comment]
Dave is writing a separate app for this, so I'm going to close this.

**Comment by rizwank** [comment]
@nbudin is this app going to be in play for 2022? I just found my old ticket for this - looks like #1466 should be closed.

**Comment by dkapell** [comment]
That's really a question for me, and I'm not sure?  I'd like to get to it
this winter, but i have a lot on my plate

**Comment by nbudin** [comment]
@rizwank Yeah, you're right - I'll close #1466.
