### ISSUE TITLE
Queued event formatting is not in signup status legend

### ISSUE THREAD

**Issue by aaazalea** [neinteractiveliterature/intercode#9160]
Signup status legend:

<img width="427" alt="Screenshot 2024-07-05 at 3 46 46 PM" src="https://github.com/neinteractiveliterature/intercode/assets/4698687/554ee5af-407e-4213-8d33-60a23f310b1a">

Queued event:

<img width="406" alt="Screenshot 2024-07-05 at 3 47 25 PM" src="https://github.com/neinteractiveliterature/intercode/assets/4698687/bcb07594-2a68-40eb-8f6e-f8f52c3e7d0f">

**Comment by nbudin** [comment]
Pushing the fix for this now!  It should be online in production within about 5 minutes.

I noticed a weird formatting issue while working on this, where the bottom of the circle is cut off (at least in Firefox on Mac).  I wasn't able to figure out why this is happening, but I figured I should at least push this and not let the perfect be the enemy of the good.
