### ISSUE TITLE
Unable to apply a comp for an event

### ISSUE THREAD

**Issue by chadberg** [neinteractiveliterature/intercode#9257]
Context: Intercon W
Objective: To apply a comp from "🕯️🌙 The Shadow Soiree"
Expected result: Comp applied to a user, and their badge payment refunded.
Current actual result: After clicking the "Convert to event provided badge" button on the user's profile, and typing in and selecting "The Shadow Soiree", Intercode tells me that event has 0 badges remaining to provide. This despite no comp badges being provided by this event at all.

I acknowledge the comp policy is currently under review. At this time I believe each game will still have one comp?

**Comment by dkapell** [comment]
This is because the game has zero comps, because no game at W has comps, as per the current policy.  The policy is a work in progress and will be resolved soon, but until then, games are set to zero comps, and people should not be comped.  There is no error here (except that I haven't resolved the comp policy yet, which is not an Intercode error)

**Comment by chadberg** [comment]
Current language on the site does state that policy is under review but still lists that each game will have one comp. Recommend taking down current language until review is complete. Sent from my iPhoneOn Jul 28, 2024, at 12:22 AM, Dave Kapell ***@***.***> wrote:﻿
This is because the game has zero comps, because no game at W has comps, as per the current policy.  The policy is a work in progress and will be resolved soon, but until then, games are set to zero comps, and people should not be comped.  There is no error here (except that I haven't resolved the comp policy yet, which is not an Intercode error)
